// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.intsidentspring.entities;

import java.lang.String;

privileged aspect Objekt_Roo_JavaBean {
    
    public String Objekt.getNimetus() {
        return this.nimetus;
    }
    
    public void Objekt.setNimetus(String nimetus) {
        this.nimetus = nimetus;
    }
    
}
