// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.intsidentspring.entities;

import java.lang.String;

privileged aspect TEST_DONOTDELETE_Roo_JavaBean {
    
    public String TEST_DONOTDELETE.getName() {
        return this.name;
    }
    
    public void TEST_DONOTDELETE.setName(String name) {
        this.name = name;
    }
    
}
