// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.intsidentspring.web;

import ee.itcollege.intsidentspring.entities.TEST_DONOTDELETE;
import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TEST_DONOTDELETEController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String TEST_DONOTDELETEController.create(@Valid TEST_DONOTDELETE TEST_DONOTDELETE, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("TEST_DONOTDELETE", TEST_DONOTDELETE);
            return "test_donotdeletes/create";
        }
        uiModel.asMap().clear();
        TEST_DONOTDELETE.persist();
        return "redirect:/test_donotdeletes/" + encodeUrlPathSegment(TEST_DONOTDELETE.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String TEST_DONOTDELETEController.createForm(Model uiModel) {
        uiModel.addAttribute("TEST_DONOTDELETE", new TEST_DONOTDELETE());
        return "test_donotdeletes/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String TEST_DONOTDELETEController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("test_donotdelete", TEST_DONOTDELETE.findTEST_DONOTDELETE(id));
        uiModel.addAttribute("itemId", id);
        return "test_donotdeletes/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String TEST_DONOTDELETEController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("test_donotdeletes", TEST_DONOTDELETE.findTEST_DONOTDELETEEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) TEST_DONOTDELETE.countTEST_DONOTDELETEs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("test_donotdeletes", TEST_DONOTDELETE.findAllTEST_DONOTDELETEs());
        }
        return "test_donotdeletes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String TEST_DONOTDELETEController.update(@Valid TEST_DONOTDELETE TEST_DONOTDELETE, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("TEST_DONOTDELETE", TEST_DONOTDELETE);
            return "test_donotdeletes/update";
        }
        uiModel.asMap().clear();
        TEST_DONOTDELETE.merge();
        return "redirect:/test_donotdeletes/" + encodeUrlPathSegment(TEST_DONOTDELETE.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String TEST_DONOTDELETEController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("TEST_DONOTDELETE", TEST_DONOTDELETE.findTEST_DONOTDELETE(id));
        return "test_donotdeletes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String TEST_DONOTDELETEController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        TEST_DONOTDELETE.findTEST_DONOTDELETE(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/test_donotdeletes";
    }
    
    @ModelAttribute("test_donotdeletes")
    public Collection<TEST_DONOTDELETE> TEST_DONOTDELETEController.populateTEST_DONOTDELETEs() {
        return TEST_DONOTDELETE.findAllTEST_DONOTDELETEs();
    }
    
    String TEST_DONOTDELETEController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
